version: '3'
services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    hostname: grafana
    container_name: grafana
    ports:
      - '3000:3000'
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/