scrape_configs:
 - job_name:       'bonita'
   # metrics_path /prometheus
  
   # Override the global default and scrape targets from this job every 5 seconds.
   scrape_interval: 5s

   static_configs:
     - targets: ['192.168.0.95:8082']
       labels:
         group: 'bonita'
