{
 "title": "Bonita Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_bonitasoft_engine_case_execution_time_seconds_max",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Connector Executions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_bonitasoft_engine_connector_executed_total",
     "legendFormat": "Connectors"
    }
   ]
  },
  {
   "title": "Work queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_bonitasoft_engine_work_pending",
     "legendFormat": "Pending works"
    }
   ]
  },
  {
   "title": "Max Connector Execution TIme",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "org_bontiasoft_engine_connector_execution_time_seconds_max"
    }
   ]
  },
  {
   "title": "Total Works Executions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_bonitasoft_engine_work_executed_total",
     "legendFormat": "Works"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Message Executions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_bonitasoft_engine_message_executed_total",
     "legendFormat": "Messages"
    }
   ]
  }
 ]
}